version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgre
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: 2doexamendb
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: